"""initial_mvp_schema

Revision ID: d7bd4ee90139
Revises: 
Create Date: 2026-09-02 15:21:44.079488+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7bd4ee90139'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('parent_company', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='competitor_intel'
    )
    op.create_index('idx_competitors_name', 'competitors', ['name'], unique=False, schema='competitor_intel')
    op.create_index('idx_competitors_norm_name', 'competitors', ['normalized_name'], unique=False, schema='competitor_intel')
    op.create_table('entity_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('source_value', sa.String(length=255), nullable=False),
    sa.Column('canonical_entity_id', sa.UUID(), nullable=False),
    sa.Column('match_method', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='competitor_intel'
    )
    op.create_index('idx_entity_mapping_type_val', 'entity_mapping', ['entity_type', 'source_value'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_entity_mapping_canonical_entity_id'), 'entity_mapping', ['canonical_entity_id'], unique=False, schema='competitor_intel')
    op.create_table('retailers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='competitor_intel'
    )
    op.create_index('idx_retailers_name', 'retailers', ['name'], unique=False, schema='competitor_intel')
    op.create_index('idx_retailers_norm_name', 'retailers', ['normalized_name'], unique=False, schema='competitor_intel')
    op.create_table('review_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='competitor_intel'
    )
    op.create_index('idx_review_queue_status', 'review_queue', ['status'], unique=False, schema='competitor_intel')
    op.create_table('source_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('crawl_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('robots_allowed', sa.Boolean(), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='competitor_intel'
    )
    op.create_index(op.f('ix_competitor_intel_source_registry_domain'), 'source_registry', ['domain'], unique=False, schema='competitor_intel')
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor_intel.competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='competitor_intel'
    )
    op.create_index('idx_brands_name', 'brands', ['name'], unique=False, schema='competitor_intel')
    op.create_index('idx_brands_norm_name', 'brands', ['normalized_name'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_brands_competitor_id'), 'brands', ['competitor_id'], unique=False, schema='competitor_intel')
    op.create_table('crawl_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['competitor_intel.source_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='competitor_intel'
    )
    op.create_index(op.f('ix_competitor_intel_crawl_jobs_source_id'), 'crawl_jobs', ['source_id'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_crawl_jobs_status'), 'crawl_jobs', ['status'], unique=False, schema='competitor_intel')
    op.create_table('crawl_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crawl_job_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('raw_content_uri', sa.Text(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['competitor_intel.crawl_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['competitor_intel.source_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='competitor_intel'
    )
    op.create_index('idx_crawl_documents_content_hash', 'crawl_documents', ['content_hash'], unique=False, schema='competitor_intel')
    op.create_index('idx_crawl_documents_url', 'crawl_documents', ['url'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_crawl_documents_crawl_job_id'), 'crawl_documents', ['crawl_job_id'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_crawl_documents_source_id'), 'crawl_documents', ['source_id'], unique=False, schema='competitor_intel')
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('variant', sa.String(length=100), nullable=True),
    sa.Column('pack_size_value', sa.Float(), nullable=True),
    sa.Column('pack_size_unit', sa.String(length=20), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['competitor_intel.brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='competitor_intel'
    )
    op.create_index('idx_products_category', 'products', ['category'], unique=False, schema='competitor_intel')
    op.create_index('idx_products_name', 'products', ['name'], unique=False, schema='competitor_intel')
    op.create_index('idx_products_norm_name', 'products', ['normalized_name'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_products_barcode'), 'products', ['barcode'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_products_brand_id'), 'products', ['brand_id'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_products_sku'), 'products', ['sku'], unique=False, schema='competitor_intel')
    op.create_table('promotion_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['competitor_intel.crawl_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='competitor_intel'
    )
    op.create_index(op.f('ix_competitor_intel_promotion_observations_document_id'), 'promotion_observations', ['document_id'], unique=False, schema='competitor_intel')
    op.create_table('promotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('retailer_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('pack_size', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('regular_price', sa.Float(), nullable=True),
    sa.Column('promo_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('promotion_type', sa.String(length=50), nullable=False),
    sa.Column('buy_quantity', sa.Integer(), nullable=True),
    sa.Column('free_quantity', sa.Integer(), nullable=True),
    sa.Column('bundle_quantity', sa.Integer(), nullable=True),
    sa.Column('cashback_amount', sa.Float(), nullable=True),
    sa.Column('voucher_amount', sa.Float(), nullable=True),
    sa.Column('minimum_purchase_amount', sa.Float(), nullable=True),
    sa.Column('minimum_purchase_quantity', sa.Integer(), nullable=True),
    sa.Column('gift_description', sa.Text(), nullable=True),
    sa.Column('promotion_title', sa.String(length=255), nullable=True),
    sa.Column('promotion_description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('geography', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_reliability', sa.Float(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['competitor_intel.brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor_intel.competitors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['competitor_intel.products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retailer_id'], ['competitor_intel.retailers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='competitor_intel'
    )
    op.create_index('idx_promotions_active_top', 'promotions', ['status', 'end_date', 'last_seen_at', 'rank_score'], unique=False, schema='competitor_intel')
    op.create_index('idx_promotions_category', 'promotions', ['category'], unique=False, schema='competitor_intel')
    op.create_index('idx_promotions_end_date', 'promotions', ['end_date'], unique=False, schema='competitor_intel')
    op.create_index('idx_promotions_last_seen', 'promotions', ['last_seen_at'], unique=False, schema='competitor_intel')
    op.create_index('idx_promotions_rank_score', 'promotions', ['rank_score'], unique=False, schema='competitor_intel')
    op.create_index('idx_promotions_status', 'promotions', ['status'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_promotions_brand_id'), 'promotions', ['brand_id'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_promotions_competitor_id'), 'promotions', ['competitor_id'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_promotions_product_id'), 'promotions', ['product_id'], unique=False, schema='competitor_intel')
    op.create_index(op.f('ix_competitor_intel_promotions_retailer_id'), 'promotions', ['retailer_id'], unique=False, schema='competitor_intel')
    op.create_table('promotion_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('promotion_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['competitor_intel.crawl_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promotion_id'], ['competitor_intel.promotions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='competitor_intel'
    )
    op.create_index(op.f('ix_competitor_intel_promotion_evidence_promotion_id'), 'promotion_evidence', ['promotion_id'], unique=False, schema='competitor_intel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_intel_promotion_evidence_promotion_id'), table_name='promotion_evidence', schema='competitor_intel')
    op.drop_table('promotion_evidence', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_promotions_retailer_id'), table_name='promotions', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_promotions_product_id'), table_name='promotions', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_promotions_competitor_id'), table_name='promotions', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_promotions_brand_id'), table_name='promotions', schema='competitor_intel')
    op.drop_index('idx_promotions_status', table_name='promotions', schema='competitor_intel')
    op.drop_index('idx_promotions_rank_score', table_name='promotions', schema='competitor_intel')
    op.drop_index('idx_promotions_last_seen', table_name='promotions', schema='competitor_intel')
    op.drop_index('idx_promotions_end_date', table_name='promotions', schema='competitor_intel')
    op.drop_index('idx_promotions_category', table_name='promotions', schema='competitor_intel')
    op.drop_index('idx_promotions_active_top', table_name='promotions', schema='competitor_intel')
    op.drop_table('promotions', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_promotion_observations_document_id'), table_name='promotion_observations', schema='competitor_intel')
    op.drop_table('promotion_observations', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_products_sku'), table_name='products', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_products_brand_id'), table_name='products', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_products_barcode'), table_name='products', schema='competitor_intel')
    op.drop_index('idx_products_norm_name', table_name='products', schema='competitor_intel')
    op.drop_index('idx_products_name', table_name='products', schema='competitor_intel')
    op.drop_index('idx_products_category', table_name='products', schema='competitor_intel')
    op.drop_table('products', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_crawl_documents_source_id'), table_name='crawl_documents', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_crawl_documents_crawl_job_id'), table_name='crawl_documents', schema='competitor_intel')
    op.drop_index('idx_crawl_documents_url', table_name='crawl_documents', schema='competitor_intel')
    op.drop_index('idx_crawl_documents_content_hash', table_name='crawl_documents', schema='competitor_intel')
    op.drop_table('crawl_documents', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_crawl_jobs_status'), table_name='crawl_jobs', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_crawl_jobs_source_id'), table_name='crawl_jobs', schema='competitor_intel')
    op.drop_table('crawl_jobs', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_brands_competitor_id'), table_name='brands', schema='competitor_intel')
    op.drop_index('idx_brands_norm_name', table_name='brands', schema='competitor_intel')
    op.drop_index('idx_brands_name', table_name='brands', schema='competitor_intel')
    op.drop_table('brands', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_source_registry_domain'), table_name='source_registry', schema='competitor_intel')
    op.drop_table('source_registry', schema='competitor_intel')
    op.drop_index('idx_review_queue_status', table_name='review_queue', schema='competitor_intel')
    op.drop_table('review_queue', schema='competitor_intel')
    op.drop_index('idx_retailers_norm_name', table_name='retailers', schema='competitor_intel')
    op.drop_index('idx_retailers_name', table_name='retailers', schema='competitor_intel')
    op.drop_table('retailers', schema='competitor_intel')
    op.drop_index(op.f('ix_competitor_intel_entity_mapping_canonical_entity_id'), table_name='entity_mapping', schema='competitor_intel')
    op.drop_index('idx_entity_mapping_type_val', table_name='entity_mapping', schema='competitor_intel')
    op.drop_table('entity_mapping', schema='competitor_intel')
    op.drop_index('idx_competitors_norm_name', table_name='competitors', schema='competitor_intel')
    op.drop_index('idx_competitors_name', table_name='competitors', schema='competitor_intel')
    op.drop_table('competitors', schema='competitor_intel')
    # ### end Alembic commands ###
